version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5435:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080